'''Свечников Илья 0304'''
from tkinter import *


window = Tk()
window.title("Action")

lbl_0 = Label(window, text="Популяция", font=("Arial Bold", 25))
lbl_1 = Label(window, text="Значение", font=("Arial Bold", 25))
lbl_2 = Label(window, text="Приспособленность", font=("Arial Bold", 25))
lbl_3 = Label(window, text="Кроссинговер", font=("Arial Bold", 25))
lbl_4 = Label(window, text="Родители", font=("Arial Bold", 25))
lbl_5 = Label(window, text="Потомки", font=("Arial Bold", 25))
lbl_6 = Label(window, text="Родители", font=("Arial Bold", 25))
lbl_7 = Label(window, text="Потомки", font=("Arial Bold", 25))
lbl_8 = Label(window, text="Родители", font=("Arial Bold", 25))
lbl_9 = Label(window, text="Потомки", font=("Arial Bold", 25))
lbl_10 = Label(window, text="Родители", font=("Arial Bold", 25))
lbl_11 = Label(window, text="Потомки", font=("Arial Bold", 25))
lbl_12 = Label(window, text="Мутация Потомков", font=("Arial Bold", 25))
lbl_13 = Label(window, text="Новая Популяция", font=("Arial Bold", 25))
lbl_14 = Label(window, text="Значение", font=("Arial Bold", 25))
lbl_15 = Label(window, text="Приспособленность", font=("Arial Bold", 25))

Ent_0 = Entry(window)
Ent_1 = Entry(window)
Ent_2 = Entry(window)
Ent_3 = Entry(window)
Ent_4 = Entry(window)
Ent_5 = Entry(window)
Ent_6 = Entry(window)
Ent_7 = Entry(window)
Ent_8 = Entry(window)
Ent_9 = Entry(window)
Ent_10 = Entry(window)
Ent_11 = Entry(window)
Ent_12 = Entry(window)
Ent_13 = Entry(window)
Ent_14 = Entry(window)
Ent_15 = Entry(window)
Ent_16 = Entry(window)
Ent_17 = Entry(window)
Ent_18 = Entry(window)
Ent_19 = Entry(window)
Ent_20 = Entry(window)
Ent_21 = Entry(window)
Ent_22 = Entry(window)
Ent_23 = Entry(window)
Ent_24 = Entry(window)
Ent_25 = Entry(window)
Ent_26 = Entry(window)
Ent_27 = Entry(window)

btn_1 = Button(window, text="Перейти К Финалу", font=("Arial Bold", 20), width=20, height=1)
btn_2 = Button(window, text="Следующий Шаг", font=("Arial Bold", 20), width=20, height=1)

lbl_0.grid(row=0, column=1, columnspan=7)
lbl_1.grid(row=1, column=0)
lbl_2.grid(row=2, column=0)
lbl_3.grid(row=3, column=1, columnspan=7)
lbl_4.grid(row=4, column=1)
lbl_5.grid(row=4, column=2)
lbl_6.grid(row=4, column=3)
lbl_7.grid(row=4, column=4)
lbl_8.grid(row=6, column=1)
lbl_9.grid(row=6, column=2)
lbl_10.grid(row=6, column=3)
lbl_11.grid(row=6, column=4)
lbl_12.grid(row=8, column=1, columnspan=8)
lbl_13.grid(row=10, column=1, columnspan=8)
lbl_14.grid(row=11, column=0)
lbl_15.grid(row=12, column=0)

Ent_0.grid(row=1, column=1)
Ent_1.grid(row=1, column=2)
Ent_2.grid(row=1, column=3)
Ent_3.grid(row=1, column=4)
Ent_4.grid(row=2, column=1)
Ent_5.grid(row=2, column=2)
Ent_6.grid(row=2, column=3)
Ent_7.grid(row=2, column=4)
Ent_8.grid(row=5, column=1)
Ent_9.grid(row=5, column=2)
Ent_10.grid(row=5, column=3)
Ent_11.grid(row=5, column=4)
Ent_12.grid(row=7, column=1)
Ent_13.grid(row=7, column=2)
Ent_14.grid(row=7, column=3)
Ent_15.grid(row=7, column=4)
Ent_16.grid(row=9, column=1)
Ent_17.grid(row=9, column=2)
Ent_18.grid(row=9, column=3)
Ent_19.grid(row=9, column=4)
Ent_20.grid(row=11, column=1)
Ent_21.grid(row=11, column=2)
Ent_22.grid(row=11, column=3)
Ent_23.grid(row=11, column=4)
Ent_24.grid(row=12, column=1)
Ent_25.grid(row=12, column=2)
Ent_26.grid(row=12, column=3)
Ent_27.grid(row=12, column=4)

btn_1.grid(row=13, column=0, columnspan=2, stick='e')
btn_2.grid(row=13, column=2, columnspan=4)


window.mainloop()
